import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { ThemeProvider } from "./components/ThemeProvider";
import Providers from "./providers/providers";

const kumbhSans = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "DevJobs",
  description: "Generated by Iga Tunde",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${kumbhSans.variable} antialiased min-h-screen `}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <div className="px-6 sm:px-6 lg:px-24 transition-all duration-300">
            <Providers>{children}</Providers>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
