import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { ThemeProvider } from "./components/ThemeProvider";


const kumbhSans = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "DevJobs",
  description: "Generated by Iga Tunde",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${kumbhSans.variable} antialiased min-h-screen `}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Header />
        <div className="px-4 sm:px-6 lg:px-32">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
